export const conversations = [
  {
    id: 1,
    user: {
      name: 'Clark Smith',
      photo: '/img/avatars/3.svg',
      role: 'UI/UX Designer',
      bio: 'Clark is a UI/UX Designer based in New York. He has 10+ years of experience in the field.',
      age: 32,
      location: 'New York',
    },
    messages: [
      {
        type: 'separator',
        text: '',
        time: 'Yesterday',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Hey Maya, I was wondering if you still had that design that you sent me a few days ago. I was thinking about using it for a project I’m working on.',
        time: '10:04 am',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'Hey Clark, sure thing. I’ll send it to you right now. I can also send you the Figma file if you need it.',
        time: '10:09 am',
        attachments: [
          {
            type: 'link',
            image: '/img/ux/13.png',
            url: 'https://figma.com',
            text: 'Figma design file by Maya',
          },
        ],
      },
      {
        type: 'separator',
        text: '',
        time: 'Today',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Thanks for that. This looks completely amazing. I’ll let you know if I need anything else.',
        time: '1:39 pm',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Almost forgot, what was that accounting company you mentioned the other day? I kinda fell in love with their design.',
        time: '1:48 pm',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'Oh yeah, that was Titan Accounting. They’re a great company. I’ve been working with them for a while now.',
        time: '2:06 pm',
        attachments: [
          {
            type: 'link',
            image: '/img/ux/11.png',
            url: 'https://waveapps.com',
            text: 'Smart Accounting made easy for everyone',
          },
        ],
      },
      {
        type: 'received',
        text: 'Yeah, that\'s them. they really have a gorgeous branding. I\'ll check them out. Thanks for the tip!',
        time: '2:16 pm',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'Always happy to help! Let me know if you need anything else.',
        time: '2:26 pm',
        attachments: [],
      },
    ],
  },
  {
    id: 2,
    user: {
      name: 'Hermann Mayer',
      photo: '/img/avatars/16.svg',
      role: 'Project Manager',
      bio: 'Hermann is a Project Manager based in Berlin. He has 10+ years of experience in the field.',
      age: 28,
      location: 'Berlin',
    },
    messages: [
      {
        type: 'separator',
        text: '',
        time: 'Yesterday',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Hey Maya, did you receive that report that John wrote? I just approved it but I wanted to show it to you, just in case you have some insights to share.',
        time: '11:04 am',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'Yeah, I\'ve got a copy on my inbox but I still didn\'t get a chance to read it and to take some notes.',
        time: '11:09 am',
        attachments: [],
      },
      {
        type: 'separator',
        text: '',
        time: 'Today',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Did you habe time to read it? The boss is asking for it and Iam not sure if I should send it.',
        time: '3:39 pm',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Sorry if Iam annoying you btw. 🫡',
        time: '3:48 pm',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'Nah, don\'t be like that! You\'re not annoying me at all. I\'m just a bit busy right now. I\'ll send you my notes but yeah, I don\'t see anything preventing you from showing it to the boss.',
        time: '4:06 pm',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Amazing! Thank you so much Maya! I really appreciate it. 🙏',
        time: '4:16 pm',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'You\'re very welcome Hermann! Let me know if you need anything else.',
        time: '4:26 pm',
        attachments: [],
      },
    ],
  },
  {
    id: 3,
    user: {
      name: 'Clarissa Miller',
      photo: '/img/avatars/5.svg',
      role: 'Product Manager',
      bio: 'Clarissa is a Product Manager based in Seattle. She has 10+ years of experience in the field.',
      age: 31,
      location: 'Seattle',
    },
    messages: [
      {
        type: 'separator',
        text: '',
        time: 'Yesterday',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Hey Maya, the boss is putting me under pressure again. He wants me to send him the report that you wrote a few days ago. I was wondering if you still had that design that you sent me a few days ago. I was thinking about using it for a project I’m working on.',
        time: '11:04 am',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'Clarissa! sure thing. I\'ll send it to you right now. weren\'t we supposed to have lunch together? I\'m free today if you want to grab a bite.',
        time: '11:09 am',
        attachments: [],
      },
      {
        type: 'separator',
        text: '',
        time: 'Today',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Sorry about yesterday, I was completely underwater. I’m free today as well. Let’s grab a bite at 2pm. I’ll send you the address.',
        time: '1:09 pm',
        attachments: [],
      },
      {
        type: 'received',
        text: 'I want to try that little sushi place that I told you about. I’m starving!',
        time: '1:09 pm',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'Oh yeah! Let\'s do suchi! I\'m starving too. I\'ll see you at 2pm.\'',
        time: '1:12 pm',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Thank you so much and sorry again about yesterday. 🙏',
        time: '1:16 pm',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'Don\'t worry about it 😉 ',
        time: '4:26 pm',
        attachments: [],
      },
    ],
  },
  {
    id: 4,
    user: {
      name: 'Joshua Stevens',
      photo: '/img/avatars/11.svg',
      role: 'Frontend Developer',
      bio: 'Joshua is a Frontend Developer based in London. He has 10+ years of experience in the field',
      age: 43,
      location: 'London',
    },
    messages: [
      {
        type: 'separator',
        text: '',
        time: 'Yesterday',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Hey Maya, the client is giving me a hard time again. He wants me to present the proposal that you worked on last week. Do you still have that presentation? I was thinking about using it for this new project.',
        time: '9:04 am',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'Hey, no problem. I still have it. I\'ll send it to you right now. How about we grab lunch today? I\'m free around noon.',
        time: '9:09 am',
        attachments: [],
      },
      {
        type: 'separator',
        text: '',
        time: 'Today',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Sorry about yesterday, I was swamped with work. I’m free today as well. Let’s grab lunch at 12pm. Meet you at the food court?',
        time: '11:09 am',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'Sounds good. See you at 12pm at the food court.',
        time: '11:12 am',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Thanks for understanding. And thank you for sending me the proposal. 🙏',
        time: '11:16 am',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'No problem. Let\'s chat more at lunch. 😉 ',
        time: '12:01 pm',
        attachments: [],
      },
    ],
  },
  {
    id: 5,
    user: {
      name: 'Kendra Wilson',
      photo: '/img/avatars/10.svg',
      role: 'Backend Developer',
      bio: 'Kendra is a Backend Developer based in Toronto. She has 10+ years of experience in the field',
      age: 26,
      location: 'Toronto',
    },
    messages: [
      {
        type: 'separator',
        text: '',
        time: 'Yesterday',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Hey, I wanted to get your feedback on the new UI design for the login page. I\'ve made some updates based on the user testing data we collected last week.',
        time: '4:04 pm',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'Sure thing, I\'ll take a look at it now. Can you send me the updated version?',
        time: '4:09 pm',
        attachments: [],
      },
      {
        type: 'separator',
        text: '',
        time: 'Today',
        attachments: [],
      },
      {
        type: 'received',
        text: 'I\'ve sent the updated version to you. I also included some notes on the changes I made.',
        time: '9:00 am',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'Thanks, I\'ll take a look now.',
        time: '9:01 am',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'I think the updates look great. I especially like the new color scheme. But I think we should also add some hover effects to the buttons to make it more interactive.',
        time: '9:15 am',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Thanks for the feedback, I\'ll add the hover effects to the buttons. Do you have time to meet later to discuss any other changes?',
        time: '9:20 am',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'Sure, let\'s schedule a meeting for 1pm today.',
        time: '9:22 am',
        attachments: [],
      },
    ],
  },
  {
    id: 6,
    user: {
      name: 'Carolin Kottmann',
      photo: '/img/avatars/9.svg',
      role: 'Product Manager',
      bio: 'Carolin is a Product manager based in Paris. She has 10+ years of experience in the field',
      age: 25,
      location: 'Paris',
    },
    messages: [
      {
        type: 'separator',
        text: '',
        time: 'Yesterday',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Hey, have you had a chance to review the market research report for the new product launch?',
        time: '4:04 pm',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'Yes, I\'ve gone through it. The data looks promising. We should schedule a meeting to discuss next steps.',
        time: '4:09 pm',
        attachments: [],
      },
      {
        type: 'separator',
        text: '',
        time: 'Today',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'I\'ve scheduled a meeting for tomorrow at 10am to discuss the launch strategy for the new product. Can you send me the latest version of the product roadmap before the meeting?',
        time: '9:00 am',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Sure, I\'ll send it to you now.',
        time: '9:01 am',
        attachments: [],
      },
      {
        type: 'received',
        text: 'I\'ve sent you the updated product roadmap. I\'ve also included some notes on the changes I made based on the market research.',
        time: '9:05 am',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'Thanks, I\'ll review it before tomorrow\'s meeting.',
        time: '9:06 am',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'Just a reminder, the meeting is tomorrow at 10am in the conference room.',
        time: '4:22 pm',
        attachments: [],
      },
    ],
  },
  {
    id: 7,
    user: {
      name: 'Jonathan Keppler',
      photo: '/img/avatars/8.svg',
      role: 'System Administrator',
      bio: 'Jonathan is a System Administrator based in Miami. He has 10+ years of experience in the field.',
      age: 41,
      location: 'Miami',
    },
    messages: [
      {
        type: 'separator',
        text: '',
        time: 'Yesterday',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Hey, have you noticed any strange behavior with the server lately?',
        time: '2:04 pm',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'Yes, I\'ve been getting reports of slow response times. I\'ve started investigating but haven\'t found the root cause yet.',
        time: '2:09 pm',
        attachments: [],
      },
      {
        type: 'separator',
        text: '',
        time: 'Today',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'I\'ve discovered that the server\'s disk space is almost full. I\'m going to schedule a maintenance window tonight to add more storage.',
        time: '9:00 am',
        attachments: [],
      },
      {
        type: 'received',
        text: 'Okay, I\'ll make sure to inform the team and schedule any necessary downtime.',
        time: '9:01 am',
        attachments: [],
      },
      {
        type: 'received',
        text: 'I\'ve sent an email to the team and scheduled a two-hour maintenance window starting at 11pm tonight. Will that work for you?',
        time: '9:05 am',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'Yes, that works for me. I\'ll make sure to have everything set up before the maintenance window.',
        time: '9:06 am',
        attachments: [],
      },
      {
        type: 'sent',
        text: 'I\'ve added the storage and the server is running smoothly again. I\'ll keep an eye on it and let you know if there are any further issues.',
        time: '2:22 pm',
        attachments: [],
      },
    ],
  },
]

export default defineEventHandler(() => {
  return conversations.map(conversation => ({
    id: conversation.id,
    user: conversation.user,
  }))
})
